<a href="https://colab.research.google.com/github/keehyun0613/machine_learning/blob/master/Qtable_gym_lake.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import gym
import numpy as np
import matplotlib.pyplot as plt
from gym.envs.registration import register

In [ ]:
def rargmax(vector):
    m = np.amax(vector)
    indices = np.nonzero(vector == m)[0]
    return np.random.choice(indices)


In [ ]:
env = gym.make('FrozenLake-v0')
Q = np.zeros([env.observation_space.n, env.action_space.n])
learning_rate = .85
dis = 0.95

rList = []
for episodes in range(2000):

    state = env.reset()
    rAll = 0
    done = False
    e = 1. / ((episodes // 100) + 1)

    while not done:
        action = np.argmax(Q[state, :] + np.random.randn(1, env.action_space.n) / (episodes + 1))

        new_state, reward, done, _ = env.step(action)
        Q[state, action] = (1-learning_rate) * Q[state, action] + learning_rate * (reward + dis * np.max(Q[new_state, :]))

        rAll += reward
        state = new_state
    
    rList.append(rAll)

print("Success rate: " + str(sum(rList) / 2000))
print("Final Q-Table Values")
print("LEFT DOWN RIGHT UP")
print(Q)

Success rate: 0.453
Final Q-Table Values
LEFT DOWN RIGHT UP
[[6.31494977e-02 7.64614852e-03 7.48997483e-03 5.22435800e-03]
 [8.29973659e-04 2.69759633e-06 2.07413066e-05 9.65698967e-02]
 [2.22496275e-01 6.66454479e-04 8.09734685e-04 2.35941720e-03]
 [2.48007922e-06 4.57122691e-07 6.73220460e-04 2.51476881e-03]
 [4.31721619e-01 9.95485124e-04 5.20577308e-04 1.19381702e-04]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.04354330e-01 5.44394928e-10 6.87240328e-04 5.91912855e-05]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [5.30004996e-04 4.10943951e-04 1.37558407e-03 3.63427640e-01]
 [8.18761419e-04 7.91100241e-02 0.00000000e+00 1.76848856e-04]
 [1.96008874e-01 3.13019228e-05 0.00000000e+00 1.29977162e-03]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [2.88019488e-05 2.10522336e-03 3.70061674e-01 3.59190674e-04]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 8.84153804e